# Generated by Django 4.2.7 on 2025-12-01 02:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Repartidor', 'verbose_name_plural': 'Repartidores'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address_reference',
            field=models.CharField(blank=True, help_text='Ej: Casa blanca con portón negro', max_length=255, verbose_name='Referencias'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 1, 2, 18, 9, 692874, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Pedidos'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Gastado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='driver',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 1, 2, 18, 35, 374015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/ids/', verbose_name='Foto de ID'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='En Línea'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/', verbose_name='Foto de Licencia'),
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del Admin'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('SUSPENDED', 'Suspendido')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Entregas'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ganancias Totales'),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/vehicles/', verbose_name='Foto del Vehículo'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección Principal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Actual'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Actual'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50, verbose_name='Número de Licencia'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(max_length=20, verbose_name='Placa del Vehículo'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Bicicleta'), ('MOTORCYCLE', 'Motocicleta'), ('CAR', 'Automóvil')], max_length=20, verbose_name='Tipo de Vehículo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CUSTOMER', 'Cliente'), ('DRIVER', 'Repartidor'), ('RESTAURANT', 'Restaurante')], default='CUSTOMER', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
