# Generated by Django 4.2.7 on 2025-12-08 06:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_orderrating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Asignación'), ('ASSIGNED', 'Asignado a Conductor'), ('PICKING_UP', 'Recogiendo Pedido'), ('PICKED_UP', 'Pedido Recogido'), ('IN_TRANSIT', 'En Camino al Cliente'), ('ARRIVED', 'Llegó a Destino'), ('DELIVERED', 'Entregado'), ('FAILED', 'Entrega Fallida'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('pickup_address', models.TextField(verbose_name='Dirección de Recogida')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud de Recogida')),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud de Recogida')),
                ('delivery_address', models.TextField(verbose_name='Dirección de Entrega')),
                ('delivery_reference', models.CharField(blank=True, max_length=255, verbose_name='Referencia de Entrega')),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud de Entrega')),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud de Entrega')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia total del recorrido', max_digits=6, null=True, verbose_name='Distancia Total (km)')),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Recogida')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Entrega')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Asignado en')),
                ('pickup_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Recogida')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Recogido en')),
                ('in_transit_at', models.DateTimeField(blank=True, null=True, verbose_name='En Tránsito desde')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Llegada en')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado en')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fallido en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('failure_reason', models.CharField(blank=True, choices=[('CUSTOMER_UNAVAILABLE', 'Cliente No Disponible'), ('WRONG_ADDRESS', 'Dirección Incorrecta'), ('CUSTOMER_REJECTED', 'Cliente Rechazó el Pedido'), ('ACCIDENT', 'Accidente'), ('VEHICLE_ISSUE', 'Problema con el Vehículo'), ('OTHER', 'Otro')], max_length=30, verbose_name='Razón de Falla')),
                ('failure_notes', models.TextField(blank=True, verbose_name='Notas de Falla')),
                ('failure_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/failures/', verbose_name='Foto de Evidencia de Falla')),
                ('delivery_proof_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/proofs/', verbose_name='Foto de Prueba de Entrega')),
                ('delivery_signature', models.TextField(blank=True, help_text='Datos de firma digital en formato base64', verbose_name='Firma Digital del Cliente')),
                ('delivery_notes', models.TextField(blank=True, help_text='Notas del conductor al entregar', verbose_name='Notas de Entrega')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono del Cliente')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones Especiales')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Tarifa de Entrega')),
                ('tip', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Propina')),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarifa de entrega + propina', max_digits=6, verbose_name='Ganancias del Conductor')),
                ('priority', models.IntegerField(default=0, help_text='Mayor número = mayor prioridad', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridad')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de Entrega')),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3, verbose_name='Máximo de Intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Asignación'), ('ASSIGNED', 'Asignado a Conductor'), ('PICKING_UP', 'Recogiendo Pedido'), ('PICKED_UP', 'Pedido Recogido'), ('IN_TRANSIT', 'En Camino al Cliente'), ('ARRIVED', 'Llegó a Destino'), ('DELIVERED', 'Entregado'), ('FAILED', 'Entrega Fallida'), ('CANCELLED', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.delivery', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Entrega',
                'verbose_name_plural': 'Historial de Estados de Entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('TRAFFIC', 'Tráfico Pesado'), ('WEATHER', 'Mal Clima'), ('VEHICLE', 'Problema con Vehículo'), ('ACCIDENT', 'Accidente'), ('WRONG_ADDRESS', 'Dirección Incorrecta'), ('CUSTOMER_ISSUE', 'Problema con Cliente'), ('RESTAURANT_DELAY', 'Retraso del Restaurante'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de Problema')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deliveries/issues/', verbose_name='Foto de Evidencia')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolución')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='deliveries.delivery', verbose_name='Entrega')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_delivery_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Problema de Entrega',
                'verbose_name_plural': 'Problemas de Entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('accuracy', models.FloatField(blank=True, help_text='Precisión del GPS en metros', null=True, verbose_name='Precisión (metros)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad (km/h)')),
                ('heading', models.FloatField(blank=True, help_text='Dirección del movimiento en grados (0-360)', null=True, verbose_name='Dirección (grados)')),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de Batería (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tracking', to='deliveries.delivery', verbose_name='Entrega')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Ubicación de Entrega',
                'verbose_name_plural': 'Ubicaciones de Entregas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['delivery', '-timestamp'], name='deliveries__deliver_bb67d6_idx'), models.Index(fields=['driver', '-timestamp'], name='deliveries__driver__f4310d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'created_at'], name='deliveries__status_a4e49b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'status'], name='deliveries__driver__3b562f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='deliveries__order_i_3c4f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['-priority', 'created_at'], name='deliveries__priorit_b588ad_idx'),
        ),
    ]
