# Generated by Django 4.2.7 on 2025-12-07 19:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Restaurante')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descripción del restaurante y tipo de comida', verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurants/banners/', verbose_name='Banner/Portada')),
                ('cuisine_type', models.CharField(choices=[('ECUADORIAN', 'Ecuatoriana'), ('FAST_FOOD', 'Comida Rápida'), ('PIZZA', 'Pizzería'), ('CHINESE', 'China'), ('MEXICAN', 'Mexicana'), ('ITALIAN', 'Italiana'), ('SEAFOOD', 'Mariscos'), ('GRILL', 'Parrillada'), ('CHICKEN', 'Pollo'), ('BURGER', 'Hamburguesas'), ('BREAKFAST', 'Desayunos'), ('COFFEE', 'Cafetería'), ('BAKERY', 'Panadería'), ('HEALTHY', 'Saludable'), ('VEGAN', 'Vegano'), ('DESSERTS', 'Postres'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Cocina')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('address_reference', models.CharField(blank=True, help_text='Ej: Al lado del parque central', max_length=255, verbose_name='Referencias')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyentes', max_length=20, unique=True, verbose_name='RUC')),
                ('business_license', models.ImageField(blank=True, null=True, upload_to='restaurants/licenses/', verbose_name='Permiso de Funcionamiento')),
                ('health_permit', models.ImageField(blank=True, null=True, upload_to='restaurants/health_permits/', verbose_name='Permiso Sanitario')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('SUSPENDED', 'Suspendido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Admin')),
                ('is_open', models.BooleanField(default=True, verbose_name='Abierto Ahora')),
                ('is_accepting_orders', models.BooleanField(default=True, verbose_name='Aceptando Pedidos')),
                ('delivery_time_min', models.PositiveIntegerField(default=30, help_text='En minutos', verbose_name='Tiempo Mínimo de Entrega (min)')),
                ('delivery_time_max', models.PositiveIntegerField(default=60, help_text='En minutos', verbose_name='Tiempo Máximo de Entrega (min)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envío')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=5.0, help_text='Monto mínimo para realizar un pedido', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pedido Mínimo')),
                ('free_delivery_above', models.DecimalField(blank=True, decimal_places=2, help_text='Monto para envío gratis (opcional)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Envío Gratis Desde')),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=5.0, help_text='Distancia máxima de entrega', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Radio de Entrega (km)')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total de Reseñas')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de Pedidos')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ingresos Totales')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece en la sección destacados', verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=False, help_text='Muestra badge de "Nuevo"', verbose_name='Nuevo')),
                ('has_promotion', models.BooleanField(default=False, help_text='Muestra badge de promoción', verbose_name='Tiene Promoción')),
                ('promotion_text', models.CharField(blank=True, help_text='Ej: 2x1 en pizzas', max_length=100, verbose_name='Texto de Promoción')),
                ('accepts_cash', models.BooleanField(default=True, verbose_name='Acepta Efectivo')),
                ('accepts_card', models.BooleanField(default=True, verbose_name='Acepta Tarjeta')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Tiene Estacionamiento')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Tiene WiFi')),
                ('is_eco_friendly', models.BooleanField(default=False, help_text='Usa empaques biodegradables', verbose_name='Eco-Friendly')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje que cobra la plataforma', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa de Comisión (%)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de Fotos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('opening_time', models.TimeField(verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de Cierre')),
                ('is_closed', models.BooleanField(default=False, help_text='Marcar si el restaurante está cerrado este día', verbose_name='Cerrado')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day_of_week', 'opening_time'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('food_quality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad de Comida')),
                ('delivery_time', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tiempo de Entrega')),
                ('packaging', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Empaquetado')),
                ('restaurant_response', models.TextField(blank=True, verbose_name='Respuesta del Restaurante')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('is_verified', models.BooleanField(default=False, help_text='El cliente realizó el pedido', verbose_name='Verificada')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='orders.order', verbose_name='Pedido')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
                'unique_together': {('restaurant', 'customer', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status', 'is_open'], name='restaurants_status_0104b6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['cuisine_type'], name='restaurants_cuisine_01615e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['-rating'], name='restaurants_rating_be9896_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='restaurants_latitud_bcb1fb_idx'),
        ),
    ]
