# Generated by Django 4.2.7 on 2025-12-08 05:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calificación de Pedido', 'verbose_name_plural': 'Calificaciones de Pedidos'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customizations',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Cancelación'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Cupón'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia desde el restaurante', max_digits=5, null=True, verbose_name='Distancia de Entrega (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_preparation_time',
            field=models.PositiveIntegerField(default=30, verbose_name='Tiempo Estimado de Preparación (min)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_rated',
            field=models.BooleanField(default=False, verbose_name='Calificado'),
        ),
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='En Preparación desde'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos'),
        ),
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Propina para el repartidor', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Propina'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de la transacción de pago', max_length=100, verbose_name='ID de Transacción'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total de Extras'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total de Opciones'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_extras',
            field=models.JSONField(blank=True, default=list, help_text='[{"id": 1, "name": "Extra Queso", "price": "1.50", "quantity": 1}]', verbose_name='Extras Seleccionados'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list, help_text='[{"group": "Tamaño", "option": "Grande", "price_modifier": "2.00"}]', verbose_name='Opciones Seleccionadas'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='delivery_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación de la Entrega'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='disliked_aspects',
            field=models.JSONField(blank=True, default=list, help_text='["Llegó frío", "Faltó cubiertos", etc.]', verbose_name='Aspectos Negativos'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='food_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación de la Comida'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='liked_aspects',
            field=models.JSONField(blank=True, default=list, help_text='["Rápido", "Buena presentación", etc.]', verbose_name='Aspectos Positivos'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('CUSTOMER_REQUEST', 'Solicitado por el Cliente'), ('RESTAURANT_UNAVAILABLE', 'Restaurante no Disponible'), ('DRIVER_UNAVAILABLE', 'Sin Conductor Disponible'), ('PAYMENT_FAILED', 'Fallo en el Pago'), ('OUT_OF_STOCK', 'Producto Agotado'), ('WRONG_ADDRESS', 'Dirección Incorrecta'), ('OTHER', 'Otro')], max_length=30, verbose_name='Razón de Cancelación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_reference',
            field=models.CharField(blank=True, help_text='Ej: Casa blanca con portón negro', max_length=255, verbose_name='Referencia de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa de Servicio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Notas del cliente para el restaurante o repartidor', verbose_name='Instrucciones Especiales'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Preparando'), ('READY', 'Listo para Entrega'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT', 'En Camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Ej: Sin cebolla, poco picante, etc.', verbose_name='Notas Especiales'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario Base'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid'], name='orders_orde_is_paid_921844_idx'),
        ),
    ]
