# Generated by Django 4.2.7 on 2025-12-08 06:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_orderrating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de Transacción')),
                ('transaction_type', models.CharField(choices=[('ORDER_PAYMENT', 'Pago de Pedido'), ('REFUND', 'Reembolso'), ('DRIVER_PAYOUT', 'Pago a Conductor'), ('RESTAURANT_PAYOUT', 'Pago a Restaurante'), ('TIP', 'Propina'), ('PLATFORM_FEE', 'Comisión de Plataforma')], default='ORDER_PAYMENT', max_length=30, verbose_name='Tipo de Transacción')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta de Crédito/Débito'), ('WALLET', 'Billetera Digital'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('MERCADOPAGO', 'MercadoPago')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('PARTIALLY_REFUNDED', 'Parcialmente Reembolsado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('currency', models.CharField(default='USD', help_text='Código ISO de la moneda (USD, EUR, etc.)', max_length=3, verbose_name='Moneda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Costo de Envío')),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Tarifa de Servicio')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Impuestos')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Descuento')),
                ('tip', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Propina')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión que se queda la plataforma', max_digits=8, verbose_name='Comisión de Plataforma')),
                ('restaurant_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que recibe el restaurante', max_digits=10, verbose_name='Monto para Restaurante')),
                ('driver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que recibe el conductor', max_digits=6, verbose_name='Monto para Conductor')),
                ('card_last4', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20, verbose_name='Marca de Tarjeta')),
                ('card_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Titular')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='PayPal Transaction ID')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, verbose_name='MercadoPago Payment ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela de pago', verbose_name='Respuesta de Pasarela')),
                ('failure_reason', models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Fondos Insuficientes'), ('CARD_DECLINED', 'Tarjeta Rechazada'), ('EXPIRED_CARD', 'Tarjeta Expirada'), ('INVALID_CARD', 'Tarjeta Inválida'), ('FRAUD_DETECTION', 'Detección de Fraude'), ('NETWORK_ERROR', 'Error de Red'), ('GATEWAY_ERROR', 'Error de Pasarela'), ('TIMEOUT', 'Tiempo de Espera Agotado'), ('OTHER', 'Otro')], max_length=30, verbose_name='Razón de Falla')),
                ('failure_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Razón de Reembolso')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Reembolsado')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reembolso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallo')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Pedido')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Reembolsado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de Reembolso')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Reembolsado')),
                ('reason', models.TextField(verbose_name='Razón del Reembolso')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Refund ID')),
                ('paypal_refund_id', models.CharField(blank=True, max_length=255, verbose_name='PayPal Refund ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta de Pasarela')),
                ('failure_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Pago Original')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds_history', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de Pago')),
                ('recipient_type', models.CharField(choices=[('RESTAURANT', 'Restaurante'), ('DRIVER', 'Conductor')], max_length=20, verbose_name='Tipo de Destinatario')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(help_text='Transferencia bancaria, PayPal, etc.', max_length=50, verbose_name='Método de Pago')),
                ('bank_account_last4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos de cuenta')),
                ('stripe_payout_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payout ID')),
                ('paypal_payout_id', models.CharField(blank=True, max_length=255, verbose_name='PayPal Payout ID')),
                ('failure_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallo')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Pago Saliente',
                'verbose_name_plural': 'Pagos Salientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('PARTIALLY_REFUNDED', 'Parcialmente Reembolsado')], max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pago',
                'verbose_name_plural': 'Historial de Estados de Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CARD', 'Tarjeta'), ('BANK_ACCOUNT', 'Cuenta Bancaria'), ('PAYPAL', 'PayPal'), ('WALLET', 'Billetera Digital')], max_length=20, verbose_name='Tipo')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20, verbose_name='Marca')),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes de Expiración')),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de Expiración')),
                ('card_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Titular')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Method ID')),
                ('paypal_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de PayPal')),
                ('is_default', models.BooleanField(default=False, verbose_name='Método por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('billing_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Facturación')),
                ('billing_address', models.TextField(blank=True, verbose_name='Dirección de Facturación')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('billing_country', models.CharField(blank=True, help_text='Código ISO de 2 letras', max_length=2, verbose_name='País')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Método de Pago Guardado',
                'verbose_name_plural': 'Métodos de Pago Guardados',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'),
        ),
    ]
