# Generated by Django 4.2.7 on 2025-12-08 05:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_restaurant_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en el menú (menor número = primero)', verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['restaurant', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Para listados y vistas previas', max_length=150, verbose_name='Descripción Corta')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen Principal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio original antes del descuento', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Comparación')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de Descuento')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, no se muestra en el menú', verbose_name='Activo')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Dejar vacío para stock ilimitado', null=True, verbose_name='Cantidad en Stock')),
                ('track_inventory', models.BooleanField(default=False, verbose_name='Controlar Inventario')),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Tiempo estimado en minutos', verbose_name='Tiempo de Preparación (min)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('serving_size', models.CharField(blank=True, help_text='Ej: 250g, 1 unidad', max_length=50, verbose_name='Tamaño de Porción')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece en la sección de destacados', verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=False, help_text='Muestra badge de "Nuevo"', verbose_name='Nuevo')),
                ('is_popular', models.BooleanField(default=False, help_text='Muestra badge de "Popular"', verbose_name='Popular')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Veces Ordenado')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Calificación')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Número de Reseñas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro de la categoría', verbose_name='Orden')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['restaurant', 'category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug')),
                ('tag_type', models.CharField(choices=[('DIETARY', 'Dietético'), ('SPICE', 'Picante'), ('SPECIAL', 'Especial'), ('ALLERGEN', 'Alérgeno')], default='SPECIAL', max_length=20, verbose_name='Tipo de Etiqueta')),
                ('icon', models.CharField(blank=True, help_text='Ej: 🌱, 🌶️, ⭐', max_length=50, verbose_name='Icono/Emoji')),
                ('color', models.CharField(default='#6B7280', help_text='Ej: #FF5733', max_length=7, verbose_name='Color Hex')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Etiqueta de Producto',
                'verbose_name_plural': 'Etiquetas de Productos',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Tamaño, Tipo de Masa', max_length=100, verbose_name='Nombre del Grupo')),
                ('is_required', models.BooleanField(default=False, help_text='El cliente debe seleccionar una opción', verbose_name='Requerido')),
                ('min_selections', models.PositiveIntegerField(default=1, verbose_name='Selecciones Mínimas')),
                ('max_selections', models.PositiveIntegerField(default=1, help_text='1 = selección única, >1 = selección múltiple', verbose_name='Selecciones Máximas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Grupo de Opciones',
                'verbose_name_plural': 'Grupos de Opciones',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Opción')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Puede ser positivo (aumenta) o negativo (reduce)', max_digits=8, verbose_name='Modificador de Precio')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_default', models.BooleanField(default=False, help_text='Viene preseleccionada', verbose_name='Opción por Defecto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productoptiongroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Opción de Producto',
                'verbose_name_plural': 'Opciones de Producto',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Extra')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Adicional')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Cantidad máxima que se puede agregar', verbose_name='Cantidad Máxima')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Extra de Producto',
                'verbose_name_plural': 'Extras de Productos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='reviews/products/', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='reviews/products/', verbose_name='Imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='reviews/products/', verbose_name='Imagen 3')),
                ('is_verified', models.BooleanField(default=False, help_text='El cliente compró el producto', verbose_name='Verificada')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Cuántas personas marcaron como útil', verbose_name='Útil (conteo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='orders.orderitem', verbose_name='Item del Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas de Productos',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'customer', 'order_item')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['restaurant', 'is_active', 'is_available'], name='products_pr_restaur_586cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-orders_count'], name='products_pr_orders__a07da3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating'], name='products_pr_rating_1a2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('restaurant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'is_active'], name='products_ca_restaur_2bdcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='products_ca_order_ac6215_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'slug')},
        ),
    ]
